// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUP-TasfBA-rOuk8fGaTHuLWaJAg9ajYw',
    appId: '1:1097535391938:web:7a7ea710078dbba9a9d35b',
    messagingSenderId: '1097535391938',
    projectId: 'garbage-separator-90f59',
    authDomain: 'garbage-separator-90f59.firebaseapp.com',
    storageBucket: 'garbage-separator-90f59.appspot.com',
    measurementId: 'G-PTWHK4M2TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvLjsWG4RNz4LODPFLkS8O-xcx6hJWTis',
    appId: '1:1097535391938:android:61d8f3007dbd77e2a9d35b',
    messagingSenderId: '1097535391938',
    projectId: 'garbage-separator-90f59',
    storageBucket: 'garbage-separator-90f59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPyLQZKGm8dT2XmliqlH_CXJj2QmhvM3s',
    appId: '1:1097535391938:ios:399a4256b0055e42a9d35b',
    messagingSenderId: '1097535391938',
    projectId: 'garbage-separator-90f59',
    storageBucket: 'garbage-separator-90f59.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPyLQZKGm8dT2XmliqlH_CXJj2QmhvM3s',
    appId: '1:1097535391938:ios:399a4256b0055e42a9d35b',
    messagingSenderId: '1097535391938',
    projectId: 'garbage-separator-90f59',
    storageBucket: 'garbage-separator-90f59.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUP-TasfBA-rOuk8fGaTHuLWaJAg9ajYw',
    appId: '1:1097535391938:web:2cf80b9e11b4cba7a9d35b',
    messagingSenderId: '1097535391938',
    projectId: 'garbage-separator-90f59',
    authDomain: 'garbage-separator-90f59.firebaseapp.com',
    storageBucket: 'garbage-separator-90f59.appspot.com',
    measurementId: 'G-EEGEHFX9MD',
  );
}
